# Generated by Django 5.1.4 on 2026-04-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], default='personal', max_length=20),
        ),
    ]
