# Generated by Django 5.1.4 on 2026-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='award_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='award_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
